[project]
nav = [
    { "Home" = "index.md" },
    { "User Guide" = "user_guide.md" },
    { "API Reference" = [
        "nodes/base.md",
        "nodes/inputs.md",
        "nodes/generation.md",
        "nodes/conformers.md",
        "nodes/filters.md",
        "nodes/geometry_optimizers.md",
        "nodes/singlepoint.md",
        { "Molecular Dynamics" = [
            "nodes/molecular_dynamics/torchsim.md",
        ] },
        { "Modifiers" = [
            "nodes/modifiers/deprotonation.md",
            "nodes/modifiers/protonation.md",
            "nodes/modifiers/tautomerization.md",
        ] },
        "nodes/packing.md",
        "nodes/polymers.md",
        { "Calculators" = [
            "nodes/calculators/ase.md",
            "nodes/calculators/orca.md",
            "nodes/calculators/gpu4pyscf.md",
            "nodes/calculators/torchsim.md",
        ] },

    ] },
    { "FAQ & Troubleshooting" = "faq.md" },
    { "Contributing" = "contributing.md" },
]
site_name = "JFChemistry"
site_url = "https://tracer-lulab.github.io/jfchemistry/"
site_description = "Workflows are the future of chemistry. We are enabling users to build and manage workflows for chemical research."
site_author = "Carson Farmer"
copycopyright = "&copy; 2025 Carson Farmer"
docs_dir = "docs"
site_dir = "site"
extra_css = ["stylesheets/extra.css"]
extra_javascript = [
    "javascripts/extra.js",
    "https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js",
]

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]


[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["jfchemistry"]
[project.plugins.mkdocstrings.handlers.python.options]
backlinks = "flat"
heading_level = 1
parameter_headings = false
show_root_heading = true
show_root_toc_entry = false
show_root_full_path = false
show_symbol_type_heading = true
show_symbol_type_toc = true
show_submodules = false
summary = false
inherited_members = true
filters = ["!^_", "!^__"]
docstring_section_style = "spacy"
modernize_annotations = true
overloads_only = true
show_signature_annotations = true
separate_signature = true
show_inheritance_diagram = true
[project.theme]
features = [
    "navigation.instant",
    "navigation.instant.progress",
    "navigation.tracking",
    "navigation.tabs",
    "navigation.footer",
]
language = "en"


[project.theme.icon.admonition]
note = "octicons/tag-16"
abstract = "octicons/checklist-16"
info = "octicons/info-16"
tip = "octicons/squirrel-16"
success = "octicons/check-16"
question = "octicons/question-16"
warning = "octicons/alert-16"
failure = "octicons/x-circle-16"
danger = "octicons/zap-16"
bug = "octicons/bug-16"
example = "octicons/beaker-16"
quote = "octicons/quote-16"

[project.theme.font]
text = "Red Hat Text"
code = "JetBrains Mono"
# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
accent = "teal"
# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
accent = "teal"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
